### ISSUE TITLE
List foreign key constraints in schema view

### ISSUE THREAD

**Issue by vogti** [polypheny/Polypheny-DB#125]
Currently, foreign key constraints are only visible in the UML view of the Polypheny-UI. While the UML view nicely depicts the relation between tables, it lacks further information on the foreign key constraints (i.e. the selected enforcement options). Furthermore, it is not possible to drop foreign key constraints.

I therefore propose to also list the foreign keys in the schema view of a table. Since the set of attributes is different from other constraints (enforcement options, two sets of columns) it needs a special table for this. This view should also include the name of the foreign key and the selected enforcement options. Furthermore, it should be possible to delete foreign key constraints.

Resolving this issue should be possible without touching Polypheny-DB since there is already a method for requesting foreign key information (used by the UML view) and the `dropConstraint` command can be used for dropping foreign keys as well.

**Comment by vogti** [comment]
There is not yet SQL support for modifying foreign keys.

**Comment by herkura** [comment]
Hi, my name is Hershil  I wanted to contribute to Polypheny for GSOC'21. This seems to be a nice start for a good first issue. Can I work on it? My skills are Java (non-andriod) MySQL python ,HTML css.

**Comment by S-Harshit** [comment]
May I work on this?

**Comment by vogti** [comment]
Of course :)

**Comment by S-Harshit** [comment]
> I therefore propose to also list the foreign keys in the schema view of a table. Since the set of attributes is different from other constraints (enforcement options, two sets of columns) it needs a special table for this. This view should also include the name of the foreign key and the selected enforcement options. Furthermore, it should be possible to delete foreign key constraints.
> 

@vogti I searched the project but I am having a little trouble locating the files (that display the schema of the table after selecting it form the left sidebar) so if you can give me some hints also do I have to add another column for foreign key in the existing schema or do I have to create another table, in addition to this what are enforcement options?

**Comment by nilshansen94** [comment]
Hi @S-Harshit. Thank you for wanting to work on this issue. The schema view is found in the folder src/app/views/schema-editing. This folder contains three additional angular components. The component you want to work with is the "edit-columns" components.
As mentioned in the description of the issue, the constraints should be displayed in a new, separate table.
The current constraint enforcement types are RESTRICT and NONE and can be parsed from the response of Polypheny-DB. In the UML component (src/app(views/uml) you can see how the foreign key information is requested from Polypheny-DB (using the `crud` service).
It would also be beneficial to list the foreign keys in the "edit-source-columns" component that is found in the schema-editing folder as well. Sources in the schema view in the left sidebar are displayed with the plug-icon.

**Comment by S-Harshit** [comment]
@nilshansen94 I am not able to find a way to parse enforcement types , I checked the UML to see how Foreign key information is being requested and it is using its  ForeignKey class of the UML.model to store it but I am not able to extract value of update and delete variable that are holding the value of enforcement type inside the ForeignKey class so if you can guide me a little it would be helpful.

Also I added Foreign key table in "edit-source-column" as show in image.
![image](https://user-images.githubusercontent.com/65359506/112768147-28158780-9038-11eb-87f6-e452214ec94b.png)

Are the current columns enough or do we also need target table column, or if table is not needed I can just add another column like the "pk"  in the existing schema to specify which column is acting as foreign key.


Also if the already existing constraint view the one in the image below already lets you delete foreign key then does the purpose of the new table only to display enforcement type of foreign key and its target table/column ? or have I misunderstood the issue?
![image](https://user-images.githubusercontent.com/65359506/112768644-91969580-903a-11eb-89eb-255ef898386f.png)

**Comment by nilshansen94** [comment]
Hi @S-Harshit I updated the backend to include the enforcement types in the UML model and also removed the foreign keys from the constraints table. So the foreign keys will only be displayed in your new table. We will merge the changes soon.
It would also be good to introduce delete support (in the same way than in the other tables with a trash icon. You can use the `delete-confirm` component for this). For the delete request, you can use the existing `dropConstraint` method. The `constraintType` parameter must be "FOREIGN KEY".
It would be great to display the target table. Either by displaying it in the form `table(col1, col2)` or with two columns, one for the target table and a second one for the target columns.

**Comment by S-Harshit** [comment]
link to PR https://github.com/polypheny/Polypheny-UI/pull/43

**Comment by nilshansen94** [comment]
Hi @S-Harshit, thank you for the great work!
I have a few suggestions to change a few details (see the printscreen with some comments). It would be great to have the foreign key table below the constraints table and to have a header "Foreign keys" (I used h6). Also the table in the edit-columns view is missing an empty `<th>` element at the end (see the circle). It would also be good to change the column header "Column Name" to "Columns", so it matches the other table.
![fk](https://user-images.githubusercontent.com/28142146/113108387-3b298280-9205-11eb-854c-28ddd78018b0.png)

In the code I was wondering if it would not be better to work with the ForeignKey model for the `connections[]` field.
The code in the `ngOnInit` method looks problematic, since the `getUml` method contains asynchronous code and sets the `connections` field, while the `clearConnections` method is called after the `getUml` method and clears the `connections` field. It works because the asynchronous code is slower, but could lead to problems. It would be safer to clear the `connections` field in the `getUml` method before filling it with the new data.
The check with `stringify` and `includes` is also rather unsafe.

The current approach doesn't work for composite foreign keys. Here is an example of creating one:
```sql
CREATE TABLE "public"."aa"("a" BIGINT NOT NULL,"b" BIGINT NOT NULL,"c" BIGINT,"d" BIGINT,PRIMARY KEY ("a","b")) ON STORE "hsqldb";
CREATE TABLE "public"."bb"("a" BIGINT NOT NULL,"b" BIGINT,"c" BIGINT,"d" BIGINT,PRIMARY KEY ("a")) ON STORE "hsqldb";
ALTER TABLE "public"."bb" ADD CONSTRAINT "auto_fk_23" FOREIGN KEY ("c",d) REFERENCES "public"."aa"(a,"b") ON UPDATE RESTRICT ON DELETE RESTRICT;
```
This should lead to the following entry:
![fk2](https://user-images.githubusercontent.com/28142146/113117057-65337280-920e-11eb-94cd-10fc16da22d0.png)
