### ISSUE TITLE
Wrong store list in dataset import dialog

### ISSUE THREAD

**Issue by vogti** [polypheny/Polypheny-DB#143]
The dataset import dialog shows a list of the available adapters instead of a list of the running stores.

**Comment by nilshansen94** [comment]
The dataset import was fetching the running stores, but displaying the adapterNames instead of the uniqueNames. If I submit the uniqueName to the Polypheny-DB, it will lead to a RuntimeException:
java.lang.RuntimeException: While executing SQL [INSERT..] on JDBC sub-schema.
If you want, I can push the fixed UI (submitting the uniqueNames), so you can reproduce the error.

**Comment by vogti** [comment]
Ok, please push it. I will have a look.

**Comment by nilshansen94** [comment]
I pushed the changes.

**Comment by vogti** [comment]
Fixed on hub branch
