### ISSUE TITLE
Allow to specify colors for graphs

### ISSUE THREAD

**Issue by vogti** [polypheny/Polypheny-DB#284]
When adding information elements of type graph, the colors are always picked in the same order. It would be very beneficial if colors can be specified. This requires adding a `setColors` method to `information/src/main/java/org/polypheny/db/information/InformationGraph.java` in Polypheny-DB. Furthermore, the rendering needs to be adjusted in Polypheny-UI.

**Comment by y-martinez** [comment]
Hi! I am Ybrahin Martinez, I would like to apply to Polypheny in the GSoC 21. To start with my contribution to the community I want to work on this issue. Is it available? If so, could you please assign me it? Thanks!

**Comment by vogti** [comment]
Hi Ybrahin, welcome to Polypheny! Yes, this issue is available. I have assigned the issue to you. Please notice, that solving this issue requires changes to Polpyheny-DB and Polypheny-UI. You can find a setup-guide for a Polypheny-Db dev environment in the discussion forum. A guide for UI development is available on the website.

**Comment by y-martinez** [comment]
Hi @vogti!, thanks for the links it was very straight of setup-guide.

I am writing you because I am working on the issue and just for clarification, I need to add the ability to specify a color to elements of type graph, however, it is not very clear to me if do you want that these colors match for each label, I am asking you because, I am using a `HashMap<String, String>` to matching the color and the label, but I don't know if when you specify these colors do you will pass an Array of String with the colors, or do you want to specify them in another way?. For example, do you want to specify these colors when instantiating an object of the `InformationGraph` class?, since that would cause all calls to create an instance should be changed.

On the other hand, in the code of Polypheny-UI, in the `graph.component.ts` I need to remove the array of colors `colorList`, and consume this info of Polypheny-DB right?

**Comment by vogti** [comment]
Yes, this is correct. I would suggest adding a `InformationGraph setColors(List<GraphColors> colors)` method to the InformationGraph-class. This method then overrides a default list of colors. This avoids changing the signature of the constructor and makes setting a custom order of columns optional.

Instead of names you can also add a GraphColors Enum with some color names. It should be sufficient if there are 10-15 distinct colors. If a graph contains more elements then there are columns defined in the list, you simple start again with the first color.

**Comment by vogti** [comment]
Hi @y-martinez, is everything working fine? If you have any issues or need help getting started, please do not hesitate to either ask here or open a thread in the [discussion forum](https://github.com/polypheny/Polypheny-DB/discussions).

**Comment by sulea** [comment]
Hi @vogti. I am Attila Süle - you know me ;). This issue looks to be okay for me to start with. Your suggestions written for @y-martinez are clear. Hopefully, I can deliver a good solution in a few days - firstly I just have to try to set up the environment. If I have any questions, I will ask u here. Can you assign me? Thx.

**Comment by datomo** [comment]
Hey @sulea 
Polypheny and Polypheny-UI mostly communicate via a Rest like interface, with predefined routes in the `Crud` class in the webui module, the `InformationServer` in the information module or the `ConfigServer` in the config module depending on the use-case. These routes or endpoints are called by Polypheny-UI to Polypheny-DB.
This is done from the UI side, in so called services, which are for example the crud service in `src/app/services`.

I hope this helps. Hit me back if you have any more questions.

**Comment by sulea** [comment]
Hi, I think I will finish the ticket by tomorrow. I'm working on my own forks (both backend and frontend).
Can you explain how the merge request should be organized?

**Comment by sulea** [comment]
Hi, thank you for the support and for the assignment.
I opened two PRs. Comments are welcome :) Thanks.
https://github.com/polypheny/Polypheny-DB/pull/411
https://github.com/polypheny/Polypheny-UI/pull/74

**Comment by datomo** [comment]
Hey @sulea, sorry for the delay, no worries everything is okey. 
At the moment we have a lot of open branches with major changes, which are about to be merged, so be patient with us.

**Comment by vogti** [comment]
Fixed in #411
