### ISSUE TITLE
Query Plans can't be visualized in Google Chrome

### ISSUE THREAD

**Issue by hennlo** [polypheny/Polypheny-DB#369]
### Problem description 
As already described in the [discussions page](https://github.com/polypheny/Polypheny-DB/discussions/368), the Query Plans cannot be visualized in Google Chrome once the local storage has exceeded its quota:
`ERROR DOMException: Failed to execute 'setItem' on 'Storage': Setting the value of 'plan_1637583587703' exceeded the quota.`
![image](https://user-images.githubusercontent.com/64148462/142864401-0a4bdb20-ac82-45bf-85e6-741f041e4cfb.png)

This works on all other browsers and is problem specific to Google Chrome and its quota limitation of 5MB for stored [local storage](https://developer.chrome.com/docs/apps/offline_storage/).

### Proposal
As far as I'm concerned the query plans only need to be stored locally as long as the user has the `query tab` open.
Since this problem essentially occurs due to infrequent cleansing of the query plans in local storage.

I would propose to mitigate this by removing the individual query plan keys after the user has left the page,
since they will be unusable from that point on anyway.

### Workaround
As long as we have not permanent corrective action in place, one can simply clear the local storage for the specific sites as proposed [here](https://github.com/polypheny/Polypheny-DB/discussions/368#discussioncomment-1681211) to resolve this problem temporarily.

**Comment by hennlo** [comment]
@datomo  Maybe you could take a quick look at this?

**Comment by datomo** [comment]
Your suggested approach should be easily doable. I can implement it asap.

**Comment by datomo** [comment]
While my suggested PR would fix the problem, I see no reason to even save the query plans to localStorage to begin with.
Especially due to the fact that this is done each time when the plan view is switched to another plan, even for the same queries and the same plans.
So we could also disable this saving process, as it is not necessary and brings no benefit preformance or utility wise, as far as I can see.
Maybe @vogti knows a reason why this was integrated this way.

**Comment by vogti** [comment]
I don't know. If there is no advantage of storing them, we should of course disable this entirely.
