### ISSUE TITLE
Persistent configuration

### ISSUE THREAD

**Issue by vogti** [polypheny/Polypheny-DB#69]
> Please be aware that this is a rather large issue for first time contributers!

In the current implementation, any changes to the default values are lost after a restart of Polypheny-DB. To change this, I propose the following changes to the configuration system:

- If there are changes to the configuration (e.g. via the UI) these changes are not directly written to the configuration file but are as in the current implementation only available until the next restart. 
- To write the configuration to the config file there should be a button in the UI. Its icon should indicate whether there are unwritten configurations. By clicking on the button, the user is presented a diff between the currently active configuration and the configuration in the file.
- It should be possible to select whether the whole configuration or only those different to the default should be written to the file.
- It should also be possible to download the current configuration in the UI. The user should be able to decide whether the exported file should contain all values or only those different to the default values.
- It should be possible to trigger an import of configuration values from a file. If this is done via the UI it would be beneficial to show the changes in the form of a diff before they are applied.
- Independent of the origin of a request to update a config value (UI, file, ...) the checks have to be applied.

The existing configuration system already supports values from a file (`application.conf`) containing key-value pairs.

**Comment by schoenja** [comment]
I have been working on a custom written gradle plugin for properties generation for the CaroloCup codebase. Maybe we could reuse this here.

gist of it:
- Single source of truth for property name, type, and default value in an XML file.
- automatic generation of properties enum and java .properties file.
- gradle plugin supports incremental compilation
- nesting of properties is possible in the XML.
- there exists and XSD schema to (theoretically) validate the XML file. (but it's mostly just there so that intellij has tab completion)

things it can't do right now:
- let the program modify the settings.
- validate settings.

I can look into extracting the code for it later today, if you are interested.

**Comment by vogti** [comment]
Important is, that the solution is fully integrated into the existing configuration manager. The focus is not so much on making the configuration files easily adjustable by hand but more on preserving configuration changes done in the existing configuration system (e.g. via the UI) between restarts of Polypheny-DB.

**Comment by vogti** [comment]
Fixed in #380
