### ISSUE TITLE
UI should propose auto generated names 

### ISSUE THREAD

**Issue by vogti** [polypheny/Polypheny-DB#75]
Use #74 to propose artificially generated index, foreign key and constraint names in the UI. Those names should be set as placeholder in the corresponding input fields of the UI.

**Comment by nilshansen94** [comment]
It works (not committed yet). But the generated names get a bit ugly, because every time the user goes to the schema management or uml page, the counter of the auto generated name is increased. Would it be possible to edit the method in such a way that the counter of the generated name is only increased if necessary? Or do you want to have this feature in the UI despite the described behavior?

**Comment by vogti** [comment]
Yes, I know. But I think this is ok. It is better to make sure that we have no duplicates.
